/**
 * Session Manager for Notion MCP Server
 *
 * This module manages MCP protocol sessions, including:
 * - Transport storage and retrieval
 * - Notion token association per session
 * - Session cleanup
 *
 * The SessionManager is critical for multi-tenant support, allowing different
 * sessions to use different Notion workspaces by associating each session with
 * its own Notion integration token.
 */

import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { logger } from "../utils/logger";

/**
 * Session Manager class for MCP protocol sessions
 *
 * This class manages multiple concurrent MCP sessions, each with:
 * - A unique session ID (generated by the MCP SDK)
 * - A transport instance (handles MCP protocol communication)
 * - An optional Notion token (enables multi-tenant support)
 *
 * The SessionManager ensures:
 * - Sessions are isolated from each other
 * - Each session can use a different Notion workspace
 * - Resources are cleaned up when sessions end
 * - Token lookup is efficient for the MCP proxy
 */
export class SessionManager {
  /**
   * Map of session IDs to transport instances
   *
   * This map stores the active MCP transport for each session.
   * The transport is used to route MCP protocol messages to the correct session.
   *
   * Key: sessionId (string) - Unique session identifier from MCP SDK
   * Value: StreamableHTTPServerTransport - MCP transport instance for this session
   *
   * Example: {
   *   "session-123": <StreamableHTTPServerTransport instance>,
   *   "session-456": <StreamableHTTPServerTransport instance>
   * }
   */
  private transports: { [sessionId: string]: StreamableHTTPServerTransport } =
    {};
  /**
   * Map of session IDs to Notion integration tokens
   *
   * This map stores the Notion token associated with each session.
   * This enables multi-tenant support - different sessions can use different
   * Notion workspaces by providing different tokens.
   *
   * Key: sessionId (string) - Unique session identifier
   * Value: string - Notion integration token (e.g., "secret_abc123...")
   *
   * Example: {
   *   "session-123": "secret_token_for_workspace_a",
   *   "session-456": "secret_token_for_workspace_b"
   * }
   *
   * Note: If a session doesn't have a token here, it will use the NOTION_TOKEN
   * environment variable (backward compatibility with single-tenant mode).
   */
  private sessionTokens: { [sessionId: string]: string } = {};

  /**
   * Get transport for a session ID
   *
   * This method retrieves the MCP transport instance for a given session.
   * The transport is used by the MCP handlers to route requests to the correct
   * session. If the session doesn't exist, returns undefined (allowing the
   * caller to handle missing sessions gracefully).
   *
   * @param sessionId - The unique session identifier to look up
   * @returns The transport instance for this session, or undefined if the session doesn't exist
   */
  getTransport(sessionId: string): StreamableHTTPServerTransport | undefined {
    /**
     * Look up transport in the transports map
     *
     * If the sessionId exists as a key, returns the corresponding transport.
     * If the sessionId doesn't exist, returns undefined (JavaScript object behavior).
     * This is safe - the caller can check for undefined and handle it appropriately.
     */
    return this.transports[sessionId];
  }

  /**
   * Store a transport for a session
   *
   * This method stores a new MCP transport instance and optionally associates
   * it with a Notion token. This is called when a new MCP session is initialized.
   * The transport is stored so subsequent requests in the same session can be
   * routed to the correct transport instance.
   *
   * @param sessionId - The unique session identifier (generated by MCP SDK)
   * @param transport - The MCP transport instance to store
   * @param notionToken - Optional Notion integration token for multi-tenant support
   *                     If provided, this session will use this token instead of
   *                     the NOTION_TOKEN environment variable
   */
  storeTransport(
    sessionId: string,
    transport: StreamableHTTPServerTransport,
    notionToken?: string
  ): void {
    /**
     * Store the transport instance in the transports map
     *
     * This associates the sessionId with the transport, allowing us to
     * retrieve it later when routing requests. If a transport already exists
     * for this sessionId, it will be overwritten (shouldn't happen in normal usage).
     */
    this.transports[sessionId] = transport;

    /**
     * Store Notion token if provided (enables multi-tenant support)
     *
     * If a Notion token is provided, we store it in the sessionTokens map.
     * This allows this session to use a different Notion workspace than other
     * sessions. If no token is provided, the session will use the NOTION_TOKEN
     * environment variable (backward compatibility with single-tenant mode).
     */
    if (notionToken) {
      this.sessionTokens[sessionId] = notionToken;
    }

    /**
     * Log the transport storage for debugging
     *
     * This helps track session creation and provides visibility into how many
     * concurrent sessions are active. The log includes:
     * - component: "mcp" (identifies this as MCP-related logging)
     * - sessionId: The session that was stored
     * - transportCount: Total number of active sessions (useful for monitoring)
     */
    logger.debug("Transport stored in map", {
      component: "mcp",
      sessionId,
      transportCount: Object.keys(this.transports).length,
    });
  }

  /**
   * Update Notion token for an existing session
   *
   * This method allows updating the Notion token for an existing session.
   * This is useful when a client wants to switch Notion workspaces mid-session
   * by providing a new X-Notion-Token header in a subsequent request.
   *
   * We only update the token if the session exists (has a transport).
   * This prevents storing tokens for non-existent sessions.
   *
   * @param sessionId - The unique session identifier
   * @param notionToken - The new Notion integration token to use for this session
   */
  updateToken(sessionId: string, notionToken: string): void {
    /**
     * Check if session exists before updating token
     *
     * We verify that a transport exists for this sessionId before updating
     * the token. This ensures we only store tokens for valid, active sessions.
     * If the session doesn't exist, we silently ignore the update (no error thrown).
     */
    if (this.transports[sessionId]) {
      /**
       * Update the token in the sessionTokens map
       *
       * This overwrites any existing token for this session. Subsequent
       * Notion API calls in this session will use the new token.
       */
      this.sessionTokens[sessionId] = notionToken;
    }
  }

  /**
   * Get Notion token for a session
   *
   * This method retrieves the Notion integration token associated with a session.
   * The token is used by the MCP proxy to make Notion API calls with the correct
   * workspace credentials. If no token is stored for this session, returns undefined,
   * which signals the proxy to use the NOTION_TOKEN environment variable instead.
   *
   * @param sessionId - The unique session identifier
   * @returns The Notion integration token for this session, or undefined if not set
   *          (indicating the session should use NOTION_TOKEN env var)
   */
  getToken(sessionId: string): string | undefined {
    /**
     * Look up token in the sessionTokens map
     *
     * If the sessionId exists as a key, returns the corresponding token.
     * If the sessionId doesn't exist or has no token, returns undefined.
     * The caller (MCP proxy) interprets undefined as "use NOTION_TOKEN env var".
     */
    return this.sessionTokens[sessionId];
  }

  /**
   * Remove a session and clean up resources
   *
   * This method removes a session from both the transports and sessionTokens maps.
   * It's called when a session is closed (e.g., client disconnects, session timeout).
   * Cleaning up sessions prevents memory leaks and ensures resources are released.
   *
   * This method is safe to call even if the session doesn't exist (delete on
   * non-existent key is a no-op in JavaScript).
   *
   * @param sessionId - The unique session identifier to remove
   */
  removeSession(sessionId: string): void {
    /**
     * Remove transport from the transports map
     *
     * This deletes the transport instance, allowing it to be garbage collected.
     * After this, getTransport() will return undefined for this sessionId.
     */
    delete this.transports[sessionId];
    /**
     * Remove token from the sessionTokens map
     *
     * This deletes the Notion token, ensuring it's not kept in memory after
     * the session ends. This is important for security - tokens shouldn't
     * persist longer than necessary.
     */
    delete this.sessionTokens[sessionId];
  }

  /**
   * Get all active session IDs
   *
   * This method returns an array of all currently active session IDs.
   * This is useful for:
   * - Debugging and monitoring (how many concurrent sessions are active)
   * - Logging and metrics (track session counts)
   * - Health checks (verify sessions are being managed correctly)
   *
   * @returns Array of active session ID strings
   *          Example: ["session-123", "session-456", "session-789"]
   */
  getActiveSessions(): string[] {
    /**
     * Extract all keys from the transports map
     *
     * Object.keys() returns an array of all property names (session IDs) in the
     * transports object. Since we only add sessionIds when transports are stored,
     * this gives us all active sessions. The order is not guaranteed (JavaScript
     * object key order is insertion order for string keys, but shouldn't be relied upon).
     */
    return Object.keys(this.transports);
  }

  /**
   * Check if a session exists
   *
   * This method provides a convenient way to check if a session exists without
   * retrieving the transport. It's used by handlers to quickly validate session IDs
   * before processing requests.
   *
   * @param sessionId - The unique session identifier to check
   * @returns True if the session exists (has a transport), false otherwise
   */
  hasSession(sessionId: string): boolean {
    /**
     * Convert transport lookup to boolean
     *
     * this.transports[sessionId] returns:
     * - The transport object if the session exists (truthy)
     * - undefined if the session doesn't exist (falsy)
     *
     * The double negation (!!) converts the result to a boolean:
     * - !!transport -> true (session exists)
     * - !!undefined -> false (session doesn't exist)
     *
     * This is more explicit than just returning the transport directly.
     */
    return !!this.transports[sessionId];
  }

  /**
   * Get token lookup function for MCP proxy
   *
   * This method returns a function that can be passed to the MCP proxy's
   * setSessionTokenLookup() method. The proxy calls this function with a
   * sessionId to get the Notion token for that session when making API calls.
   *
   * Why return a function instead of the proxy calling getToken() directly?
   * - The proxy needs a function reference, not a method reference
   * - This creates a closure that captures `this.sessionTokens`
   * - The proxy can call the function without knowing about SessionManager
   * - This decouples the proxy from the SessionManager implementation
   *
   * @returns A function that takes a sessionId and returns the Notion token
   *          (or undefined if no token is stored for that session)
   *
   * Example usage:
   *   const lookup = sessionManager.getTokenLookup();
   *   proxy.setSessionTokenLookup(lookup);
   *   // Later, proxy calls: const token = lookup("session-123");
   */
  getTokenLookup(): (sessionId: string) => string | undefined {
    /**
     * Return an arrow function that captures this.sessionTokens
     *
     * The arrow function creates a closure over `this.sessionTokens`,
     * allowing it to access the map even after it's returned. When the proxy
     * calls this function with a sessionId, it looks up the token in the
     * sessionTokens map and returns it (or undefined if not found).
     *
     * This is equivalent to:
     *   return function(sessionId: string) {
     *     return this.sessionTokens[sessionId];
     *   }.bind(this);
     *
     * But arrow functions are cleaner and automatically bind `this`.
     */
    return (sessionId: string) => this.sessionTokens[sessionId];
  }
}
