/**
 * Command-line argument parser for Notion MCP Server
 *
 * This module extracts configuration from command-line arguments:
 * - --transport: Either "stdio" or "http" (defaults to "stdio")
 * - --port: Port number for HTTP server (defaults to 3000)
 * - --auth-token: Bearer token for HTTP authentication (optional)
 * - --help or -h: Display help message and exit
 *
 * The parser is designed to be:
 * - Forgiving: Ignores unrecognized arguments (useful for Docker/wrappers)
 * - Case-insensitive: Normalizes transport values to lowercase
 * - Safe: Uses defaults when values are missing
 * - User-friendly: Provides comprehensive help text
 */

/**
 * Server configuration options extracted from command-line arguments
 *
 * This interface defines the structure of the parsed configuration object
 * that is returned by parseArgs(). All fields except authToken are required.
 */
export interface ServerOptions {
  /** Transport type: "stdio" for desktop apps, "http" for web/backend services */
  transport: "stdio" | "http";
  /** Port number for HTTP server (only used when transport is "http") */
  port: number;
  /** Optional bearer token for HTTP authentication (secures endpoints) */
  authToken?: string;
}

/**
 * Parse command-line arguments
 *
 * This function extracts server configuration from command-line arguments.
 * It handles various argument formats, provides sensible defaults, and
 * gracefully handles edge cases like missing values or unrecognized arguments.
 *
 * @param args - Command-line arguments array (defaults to process.argv)
 *               Format: [node_executable, script_path, ...user_args]
 *               If not provided, uses process.argv automatically
 * @returns Object containing parsed transport, port, and authToken
 *          All values are validated and normalized before returning
 */
export function parseArgs(args: string[] = process.argv): ServerOptions {
  /**
   * Extract user-provided arguments from the full argument array
   *
   * process.argv format: [node_executable_path, script_path, ...user_args]
   * Example: ["/usr/bin/node", "/path/to/script.js", "--transport", "http"]
   *
   * We skip the first two elements because:
   * - args[0]: Path to Node.js executable (e.g., "/usr/bin/node")
   * - args[1]: Path to the script being executed (e.g., "/path/to/start-server.ts")
   * - args[2+]: User-provided arguments (what we actually want to parse)
   *
   * slice(2) returns everything from index 2 onwards, giving us only user args.
   */
  const userArgs = args.slice(2);

  /**
   * Initialize default values
   *
   * These defaults ensure the server can start even if no arguments are provided.
   * The defaults are chosen to be:
   * - Safe: Work out of the box without configuration
   * - Compatible: Support common use cases (desktop apps, local development)
   * - Sensible: Use standard ports and common transport types
   */
  // Default to STDIO transport for compatibility with desktop applications
  // STDIO allows the server to communicate via standard input/output streams
  // This is the default because many MCP clients expect STDIO communication
  let transport = "stdio";
  // Default HTTP port (only used when transport is "http")
  // Port 3000 is a common development port, unlikely to conflict
  let port = 3000;
  // No default auth token - will be undefined if not provided
  // If auth token is needed, it can be:
  // 1. Provided via --auth-token argument
  // 2. Set via AUTH_TOKEN environment variable
  // 3. Auto-generated by the server if neither is provided
  let authToken: string | undefined;

  /**
   * Iterate through all user-provided arguments
   *
   * We use a for loop with manual index increment because some arguments
   * consume two array elements (flag + value). When we find a flag with a value,
   * we increment i by 1 extra to skip the value we just consumed.
   *
   * Example: ["--transport", "http", "--port", "3000"]
   * - i=0: "--transport" -> consume "http" at i=1, then i becomes 2
   * - i=2: "--port" -> consume "3000" at i=3, then i becomes 4
   * - i=4: loop ends
   */
  for (let i = 0; i < userArgs.length; i++) {
    /**
     * Parse --transport argument
     *
     * Format: --transport <type>
     * Valid types: "stdio" or "http" (case-insensitive)
     *
     * The transport type determines how the server communicates:
     * - "stdio": Standard input/output (for desktop apps, CLI tools)
     * - "http": HTTP server (for web services, backend integrations)
     *
     * We check `i + 1 < userArgs.length` to ensure the value exists.
     * If the flag is provided without a value, we skip it and use the default.
     */
    if (userArgs[i] === "--transport" && i + 1 < userArgs.length) {
      // Extract the transport type from the next argument
      // We don't validate it here - normalization happens at the end
      transport = userArgs[i + 1];
      // Increment i to skip the value we just consumed
      // This prevents the value from being processed as a separate argument
      i++;
    } else if (userArgs[i] === "--port" && i + 1 < userArgs.length) {
      /**
       * Parse --port argument
       *
       * Format: --port <number>
       * The port number specifies which port the HTTP server should listen on.
       * Only relevant when transport is "http" (ignored for stdio transport).
       *
       * We use parseInt() with base 10 to convert the string to an integer.
       * If parsing fails (e.g., non-numeric value), parseInt returns NaN,
       * which will cause the server to fail later (acceptable - invalid config should fail).
       */
      // Parse the port number as a base-10 integer
      // parseInt() handles strings like "3000", "8080", etc.
      // If the value is not a valid number, parseInt returns NaN
      port = parseInt(userArgs[i + 1], 10);
      // Increment i to skip the port value we just consumed
      i++;
    } else if (userArgs[i] === "--auth-token" && i + 1 < userArgs.length) {
      /**
       * Parse --auth-token argument
       *
       * Format: --auth-token <token>
       * The auth token is used to secure HTTP endpoints with bearer token authentication.
       * This prevents unauthorized access to the MCP server when running in HTTP mode.
       *
       * The token is stored as-is (no transformation, no validation).
       * It's the caller's responsibility to ensure the token is secure.
       */
      // Extract the auth token from the next argument
      // Store it as-is (no hashing, no validation)
      // We trim whitespace to handle cases where tokens might have accidental newlines/spaces
      authToken = userArgs[i + 1].trim();
      // Increment i to skip the token value we just consumed
      i++;
    } else if (userArgs[i] === "--help" || userArgs[i] === "-h") {
      /**
       * Handle help flags (--help or -h)
       *
       * When users provide a help flag, we should:
       * 1. Display comprehensive usage information
       * 2. Exit the process immediately (don't start the server)
       *
       * This is standard Unix behavior - help flags are for documentation,
       * not for starting the application. Both --help (long form) and -h
       * (short form) are supported for user convenience.
       */
      /**
       * Display help message to console
       *
       * We use console.log() instead of the logger because:
       * - Help text is user-facing documentation, not a log message
       * - Users need to see this immediately in their terminal
       * - Log files might not be accessible or configured yet
       * - Help should work even if logging is broken
       *
       * The help message includes:
       * - All available command-line options
       * - Environment variable alternatives
       * - Practical examples for common use cases
       * - Default values for each option
       */
      console.log(`
Usage: notion-mcp-server [options]

Options:
  --transport <type>     Transport type: 'stdio' or 'http' (default: stdio)
  --port <number>        Port for HTTP server when using Streamable HTTP transport (default: 3000)
  --auth-token <token>   Bearer token for HTTP transport authentication (optional)
  --help, -h               Show this help message

Environment Variables:
  NOTION_TOKEN           Notion integration token (recommended)
  OPENAPI_MCP_HEADERS    JSON string with Notion API headers (alternative)
  AUTH_TOKEN             Bearer token for HTTP transport authentication (alternative to --auth-token)
  DEBUG_MODE             Set to "true" to enable verbose debug logging (default: false)

Examples:
  notion-mcp-server                                    # Use stdio transport (default)
  notion-mcp-server --transport stdio                  # Use stdio transport explicitly
  notion-mcp-server --transport http                   # Use Streamable HTTP transport on port 3000
  notion-mcp-server --transport http --port 8080       # Use Streamable HTTP transport on port 8080
  notion-mcp-server --transport http --auth-token mytoken # Use Streamable HTTP transport with custom auth token
  AUTH_TOKEN=mytoken notion-mcp-server --transport http # Use Streamable HTTP transport with auth token from env var
  DEBUG_MODE=true notion-mcp-server --transport http   # Enable debug logging
`);
      /**
       * Exit the process immediately after displaying help
       *
       * Exit code 0 means "success" - the help was displayed successfully.
       * We exit because:
       * - Help is a documentation request, not a server start request
       * - Users expect help to exit immediately (standard Unix behavior)
       * - We don't want to start the server just to show help
       *
       * Note: In tests, process.exit is mocked to prevent actual exit.
       */
      process.exit(0);
    }
    /**
     * Ignore unrecognized arguments silently
     *
     * When we encounter an argument we don't recognize, we simply skip it.
     * We don't throw an error or log a warning because:
     * - Docker and other wrappers often pass additional arguments
     * - Users might have typos, but we don't want to break their workflow
     * - Future versions might add new arguments we don't know about yet
     * - It's better to be forgiving than strict (principle of least surprise)
     *
     * Example: If Docker passes "--container-name mycontainer", we ignore it.
     * Example: If a user types "--transprot http" (typo), we ignore it and use defaults.
     */
    // No else clause needed - unrecognized arguments are simply ignored
    // The loop continues to the next iteration, processing the next argument
  }

  /**
   * Normalize and return parsed configuration
   *
   * Before returning, we normalize the transport value to lowercase.
   * This ensures case-insensitive matching - users can type "HTTP", "Http",
   * or "http" and they all work the same. This improves user experience
   * by being forgiving of case variations.
   *
   * We use a type assertion `as "stdio" | "http"` because:
   * - toLowerCase() returns a string, but we know it's one of our valid values
   * - TypeScript needs to know the narrowed type for the interface
   * - We've already validated the value is one of the two options (or defaulted to "stdio")
   *
   * Note: We don't validate that transport is actually "stdio" or "http" here.
   * If an invalid value was provided, it will be caught later when the server
   * tries to use it. This keeps the parser simple and focused on extraction.
   */
  return {
    // Normalize transport to lowercase for case-insensitive matching
    // Type assertion ensures TypeScript knows this is one of the valid values
    transport: transport.toLowerCase() as "stdio" | "http",
    // Port is already a number (parsed from string or default)
    port,
    // Auth token is either the provided string or undefined
    authToken,
  };
}
